/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/healthz': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Liveness probe */
    get: operations['healthz_healthz_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/readyz': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Readiness probe */
    get: operations['readyz_readyz_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/claims': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List claims in queue order
     * @description Cursor paginated queue listing (FR-090, FR-100).
     */
    get: operations['list_claims_v1_claims_get'];
    put?: never;
    /**
     * Register a first notification of loss
     * @description Implements FR-001 to FR-006 and runs triage (FR-020).
     */
    post: operations['register_claim_v1_claims_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/claims/{claim_reference}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Read a claim
     * @description Claim detail including triage decision, reserves and documents (FR-101).
     */
    get: operations['read_claim_v1_claims__claim_reference__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/claims/{claim_reference}/approvals': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Approve or decline a pending amount
     * @description Senior handler only (FR-043).
     */
    post: operations['create_approval_v1_claims__claim_reference__approvals_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/claims/{claim_reference}/audit-events': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Read the audit trail for a claim
     * @description Read-only, append-only evidence for second line (FR-060 to FR-062).
     */
    get: operations['list_audit_events_v1_claims__claim_reference__audit_events_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/claims/{claim_reference}/documents': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List claim documents */
    get: operations['list_documents_v1_claims__claim_reference__documents_get'];
    put?: never;
    /** Request a pre-signed upload URL */
    post: operations['request_upload_v1_claims__claim_reference__documents_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/claims/{claim_reference}/documents/{document_id}/confirm': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Confirm an upload and attach the document */
    post: operations['confirm_upload_v1_claims__claim_reference__documents__document_id__confirm_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/claims/{claim_reference}/documents/{document_id}/download-url': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Issue a short-lived download URL */
    get: operations['download_url_v1_claims__claim_reference__documents__document_id__download_url_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/claims/{claim_reference}/reserves': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read the reserve history */
    get: operations['list_reserves_v1_claims__claim_reference__reserves_get'];
    put?: never;
    /**
     * Propose or set a reserve
     * @description Applies role authority limits (FR-041, FR-042).
     */
    post: operations['create_reserve_v1_claims__claim_reference__reserves_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/claims/{claim_reference}/settlements': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Raise a settlement payment instruction
     * @description Senior handler only; bounded by the approved indemnity reserve (FR-044, FR-045).
     */
    post: operations['create_settlement_v1_claims__claim_reference__settlements_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/claims/{claim_reference}/timeline': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read the claim timeline */
    get: operations['read_timeline_v1_claims__claim_reference__timeline_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/claims/{claim_reference}/transitions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Apply a lifecycle transition
     * @description Rejects illegal transitions (FR-011) and requires reason codes (FR-014).
     */
    post: operations['create_transition_v1_claims__claim_reference__transitions_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/claims/{claim_reference}/triage': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Re-run triage
     * @description Creates a new decision rather than overwriting the previous one (FR-024).
     */
    post: operations['rerun_triage_v1_claims__claim_reference__triage_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/rule-sets/current': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read the active triage rule set */
    get: operations['current_rule_set_v1_rule_sets_current_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** Address */
    Address: {
      /** City */
      city?: string | null;
      /**
       * Country
       * @default GB
       */
      country: string;
      /** Line1 */
      line1?: string | null;
      /** Postcode */
      postcode?: string | null;
    };
    /** ApprovalCreate */
    ApprovalCreate: {
      /**
       * Decision
       * @enum {string}
       */
      decision: 'APPROVE' | 'DECLINE';
      /** Note */
      note: string;
    };
    /** AuditEventView */
    AuditEventView: {
      /** Actor Id */
      actor_id: string;
      actor_role: components['schemas']['Role'];
      /** Claim Reference */
      claim_reference: string | null;
      /** Correlation Id */
      correlation_id: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Event Type */
      event_type: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Payload */
      payload: Record<string, never>;
      /** Payload Digest */
      payload_digest: string;
    };
    /**
     * Channel
     * @enum {string}
     */
    Channel: 'CONTACT_CENTRE' | 'PORTAL' | 'BROKER' | 'MOBILE';
    /**
     * ClaimCreate
     * @description FNOL submission (FR-001).
     */
    ClaimCreate: {
      /** @default CONTACT_CENTRE */
      channel: components['schemas']['Channel'];
      /**
       * Currency
       * @default GBP
       */
      currency: string;
      /** Estimated Exposure Minor */
      estimated_exposure_minor: number;
      /**
       * Fraud Indicator
       * @default false
       */
      fraud_indicator: boolean;
      incident_location?: components['schemas']['Address'] | null;
      /**
       * Loss Datetime
       * Format: date-time
       */
      loss_datetime: string;
      /** Loss Description */
      loss_description: string;
      peril: components['schemas']['Peril'];
      /** Policy Reference */
      policy_reference: string;
      policyholder: components['schemas']['Policyholder'];
      product: components['schemas']['Product'];
    };
    /**
     * ClaimDetail
     * @description Claim detail (FR-101).
     */
    ClaimDetail: {
      channel: components['schemas']['Channel'];
      /** Claim Reference */
      claim_reference: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Currency */
      currency: string;
      /** Documents */
      documents: components['schemas']['DocumentView'][];
      /** Duplicate Suspected */
      duplicate_suspected: boolean;
      /** Estimated Exposure Minor */
      estimated_exposure_minor: number;
      /** Fraud Indicator */
      fraud_indicator: boolean;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      incident_location: components['schemas']['Address'] | null;
      /** Indemnity Reserve Minor */
      indemnity_reserve_minor: number;
      /**
       * Loss Datetime
       * Format: date-time
       */
      loss_datetime: string;
      /** Loss Description */
      loss_description: string;
      /** Payments */
      payments: components['schemas']['PaymentView'][];
      /** Pending Amount Minor */
      pending_amount_minor: number | null;
      peril: components['schemas']['Peril'];
      /** Policy Reference */
      policy_reference: string;
      policyholder: components['schemas']['Policyholder'];
      /** Policyholder Name */
      policyholder_name: string;
      /** Priority */
      priority: number | null;
      product: components['schemas']['Product'];
      /** Queue */
      queue: string | null;
      /**
       * Reported At
       * Format: date-time
       */
      reported_at: string;
      /** Reserves */
      reserves: components['schemas']['ReserveView'][];
      segment: components['schemas']['Segment'] | null;
      /** Settled Minor */
      settled_minor: number;
      sla: components['schemas']['SlaView'];
      status: components['schemas']['ClaimStatus'];
      triage: components['schemas']['TriageView'] | null;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /**
     * ClaimStatus
     * @enum {string}
     */
    ClaimStatus:
      | 'REGISTERED'
      | 'TRIAGED'
      | 'IN_ASSESSMENT'
      | 'PENDING_APPROVAL'
      | 'APPROVED'
      | 'SETTLED'
      | 'REJECTED'
      | 'WITHDRAWN'
      | 'CLOSED';
    /**
     * ClaimSummary
     * @description Queue row (FR-100).
     */
    ClaimSummary: {
      /** Claim Reference */
      claim_reference: string;
      /** Currency */
      currency: string;
      /** Duplicate Suspected */
      duplicate_suspected: boolean;
      /** Estimated Exposure Minor */
      estimated_exposure_minor: number;
      peril: components['schemas']['Peril'];
      /** Policy Reference */
      policy_reference: string;
      /** Policyholder Name */
      policyholder_name: string;
      /** Priority */
      priority: number | null;
      product: components['schemas']['Product'];
      /** Queue */
      queue: string | null;
      /**
       * Reported At
       * Format: date-time
       */
      reported_at: string;
      segment: components['schemas']['Segment'] | null;
      sla: components['schemas']['SlaView'];
      status: components['schemas']['ClaimStatus'];
    };
    /** DocumentConfirm */
    DocumentConfirm: {
      /** Checksum Sha256 */
      checksum_sha256: string;
    };
    /** DocumentCreate */
    DocumentCreate: {
      /** Content Type */
      content_type: string;
      /** Filename */
      filename: string;
      /** @default OTHER */
      kind: components['schemas']['DocumentKind'];
      /** Size Bytes */
      size_bytes: number;
    };
    /**
     * DocumentKind
     * @enum {string}
     */
    DocumentKind: 'PHOTO' | 'ESTIMATE' | 'POLICE_REPORT' | 'INVOICE' | 'CORRESPONDENCE' | 'OTHER';
    /**
     * DocumentState
     * @enum {string}
     */
    DocumentState: 'AWAITING_UPLOAD' | 'AVAILABLE';
    /** DocumentUploadTicket */
    DocumentUploadTicket: {
      document: components['schemas']['DocumentView'];
      /** Expires In Seconds */
      expires_in_seconds: number;
      /** Storage Key */
      storage_key: string;
      /** Upload Url */
      upload_url: string;
    };
    /** DocumentView */
    DocumentView: {
      /** Confirmed At */
      confirmed_at: string | null;
      /** Content Type */
      content_type: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Filename */
      filename: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      kind: components['schemas']['DocumentKind'];
      /** Size Bytes */
      size_bytes: number;
      state: components['schemas']['DocumentState'];
      /** Uploaded By */
      uploaded_by: string;
    };
    /** DownloadTicket */
    DownloadTicket: {
      /** Download Url */
      download_url: string;
      /** Expires In Seconds */
      expires_in_seconds: number;
    };
    /**
     * ErrorResponse
     * @description The single error envelope used by every endpoint (FR-091).
     */
    ErrorResponse: {
      /** Code */
      code: string;
      /** Correlation Id */
      correlation_id: string;
      /** Details */
      details?: Record<string, never>;
      /** Message */
      message: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][];
    };
    /** HealthResponse */
    HealthResponse: {
      /** Service */
      service: string;
      /**
       * Status
       * @enum {string}
       */
      status: 'ok' | 'degraded';
      /** Version */
      version: string;
    };
    /** Page[AuditEventView] */
    Page_AuditEventView_: {
      /** Items */
      items: components['schemas']['AuditEventView'][];
      /** Next Cursor */
      next_cursor?: string | null;
    };
    /** Page[ClaimSummary] */
    Page_ClaimSummary_: {
      /** Items */
      items: components['schemas']['ClaimSummary'][];
      /** Next Cursor */
      next_cursor?: string | null;
    };
    /**
     * PaymentState
     * @enum {string}
     */
    PaymentState: 'INSTRUCTED' | 'ACKNOWLEDGED' | 'FAILED';
    /** PaymentView */
    PaymentView: {
      /** Amount Minor */
      amount_minor: number;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Currency */
      currency: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Payee Name */
      payee_name: string;
      /** Payee Reference */
      payee_reference: string;
      state: components['schemas']['PaymentState'];
    };
    /**
     * Peril
     * @enum {string}
     */
    Peril:
      | 'COLLISION'
      | 'THEFT'
      | 'FIRE'
      | 'FLOOD'
      | 'ESCAPE_OF_WATER'
      | 'STORM'
      | 'ACCIDENTAL_DAMAGE'
      | 'MEDICAL'
      | 'CANCELLATION'
      | 'LIABILITY';
    /** Policyholder */
    Policyholder: {
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Full Name */
      full_name: string;
      /** Phone */
      phone?: string | null;
    };
    /**
     * Product
     * @enum {string}
     */
    Product: 'MOTOR' | 'HOME' | 'TRAVEL';
    /** ReadinessResponse */
    ReadinessResponse: {
      /** Checks */
      checks: {
        [key: string]: boolean;
      };
      /**
       * Status
       * @enum {string}
       */
      status: 'ready' | 'not_ready';
    };
    /**
     * ReasonCode
     * @enum {string}
     */
    ReasonCode:
      | 'TRIAGE_COMPLETE'
      | 'ASSESSMENT_STARTED'
      | 'APPROVAL_REQUESTED'
      | 'APPROVAL_GRANTED'
      | 'APPROVAL_DECLINED'
      | 'SETTLEMENT_ISSUED'
      | 'NO_COVER'
      | 'POLICY_LAPSED'
      | 'FRAUD_CONFIRMED'
      | 'CUSTOMER_WITHDREW'
      | 'DUPLICATE_NOTIFICATION'
      | 'FILE_COMPLETE'
      | 'REOPENED';
    /**
     * ReserveCategory
     * @enum {string}
     */
    ReserveCategory: 'INDEMNITY' | 'EXPENSE';
    /** ReserveCreate */
    ReserveCreate: {
      /** Amount Minor */
      amount_minor: number;
      /** @default INDEMNITY */
      category: components['schemas']['ReserveCategory'];
      /**
       * Currency
       * @default GBP
       */
      currency: string;
      /** Note */
      note?: string | null;
    };
    /** ReserveResult */
    ReserveResult: {
      /** Authority Limit Minor */
      authority_limit_minor: number;
      claim_status: components['schemas']['ClaimStatus'];
      /** Requires Approval */
      requires_approval: boolean;
      reserve: components['schemas']['ReserveView'];
    };
    /**
     * ReserveState
     * @enum {string}
     */
    ReserveState: 'PROPOSED' | 'APPROVED' | 'DECLINED';
    /** ReserveView */
    ReserveView: {
      /** Actor Id */
      actor_id: string;
      /** Amount Minor */
      amount_minor: number;
      category: components['schemas']['ReserveCategory'];
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Currency */
      currency: string;
      /** Decided By */
      decided_by: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Note */
      note: string | null;
      state: components['schemas']['ReserveState'];
    };
    /**
     * Role
     * @enum {string}
     */
    Role: 'claims_handler' | 'senior_handler' | 'auditor';
    /** RuleOutcomeView */
    RuleOutcomeView: {
      /** Priority */
      priority: number;
      /** Queue */
      queue: string;
      segment: components['schemas']['Segment'];
    };
    /** RuleSetView */
    RuleSetView: {
      default: components['schemas']['RuleOutcomeView'];
      /** Rules */
      rules: components['schemas']['RuleView'][];
      /** Version */
      version: string;
    };
    /** RuleView */
    RuleView: {
      /** Description */
      description: string;
      /** Id */
      id: string;
      then: components['schemas']['RuleOutcomeView'];
      /** When */
      when: {
        [key: string]: Record<string, never>;
      };
    };
    /**
     * Segment
     * @enum {string}
     */
    Segment: 'FAST_TRACK' | 'STANDARD' | 'COMPLEX' | 'SPECIAL_INVESTIGATION';
    /** SettlementCreate */
    SettlementCreate: {
      /** Amount Minor */
      amount_minor: number;
      /**
       * Currency
       * @default GBP
       */
      currency: string;
      /** Note */
      note?: string | null;
      /** Payee Name */
      payee_name: string;
      /** Payee Reference */
      payee_reference: string;
    };
    /** SlaView */
    SlaView: {
      /** Acknowledgement Due At */
      acknowledgement_due_at: string | null;
      /** Awaiting Information */
      awaiting_information: boolean;
      /** Breached */
      breached: boolean;
      /** Decision Due At */
      decision_due_at: string | null;
      /** First Contact Due At */
      first_contact_due_at: string | null;
    };
    /**
     * TimelineEntry
     * @description A projection over transitions, reserves, documents and payments (FR-101).
     */
    TimelineEntry: {
      /** Actor Id */
      actor_id: string;
      /** Detail */
      detail?: Record<string, never>;
      /**
       * Kind
       * @enum {string}
       */
      kind: 'TRANSITION' | 'TRIAGE' | 'RESERVE' | 'DOCUMENT' | 'PAYMENT';
      /**
       * Occurred At
       * Format: date-time
       */
      occurred_at: string;
      /** Summary */
      summary: string;
    };
    /** TransitionCreate */
    TransitionCreate: {
      /** Note */
      note?: string | null;
      reason_code?: components['schemas']['ReasonCode'] | null;
      target_status: components['schemas']['ClaimStatus'];
    };
    /** TransitionView */
    TransitionView: {
      /** Actor Id */
      actor_id: string;
      actor_role: components['schemas']['Role'];
      /** Correlation Id */
      correlation_id: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      from_status: components['schemas']['ClaimStatus'] | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Note */
      note: string | null;
      reason_code: components['schemas']['ReasonCode'] | null;
      to_status: components['schemas']['ClaimStatus'];
    };
    /** TriageView */
    TriageView: {
      /**
       * Decided At
       * Format: date-time
       */
      decided_at: string;
      /** Priority */
      priority: number;
      /** Queue */
      queue: string;
      /** Rule Id */
      rule_id: string;
      /** Rule Set Version */
      rule_set_version: string;
      segment: components['schemas']['Segment'];
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  healthz_healthz_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HealthResponse'];
        };
      };
    };
  };
  readyz_readyz_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ReadinessResponse'];
        };
      };
    };
  };
  list_claims_v1_claims_get: {
    parameters: {
      query?: {
        limit?: number;
        cursor?: string | null;
        status?: components['schemas']['ClaimStatus'] | null;
        segment?: components['schemas']['Segment'] | null;
        queue?: string | null;
        policy_reference?: string | null;
        breached?: boolean | null;
      };
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Page_ClaimSummary_'];
        };
      };
      /** @description Malformed request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Missing or invalid bearer token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Insufficient role */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Conflicting state or idempotency key */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Validation failed */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  register_claim_v1_claims_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
        'Idempotency-Key'?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ClaimCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ClaimDetail'];
        };
      };
      /** @description Malformed request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Missing or invalid bearer token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Insufficient role */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Conflicting state or idempotency key */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Validation failed */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  read_claim_v1_claims__claim_reference__get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        claim_reference: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ClaimDetail'];
        };
      };
      /** @description Malformed request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Missing or invalid bearer token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Insufficient role */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Conflicting state or idempotency key */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Validation failed */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  create_approval_v1_claims__claim_reference__approvals_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
        'Idempotency-Key'?: string | null;
      };
      path: {
        claim_reference: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ApprovalCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ReserveView'];
        };
      };
      /** @description Malformed request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Missing or invalid bearer token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Insufficient role */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Conflicting state or idempotency key */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Validation failed */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  list_audit_events_v1_claims__claim_reference__audit_events_get: {
    parameters: {
      query?: {
        limit?: number;
      };
      header?: {
        authorization?: string | null;
      };
      path: {
        claim_reference: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Page_AuditEventView_'];
        };
      };
      /** @description Malformed request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Missing or invalid bearer token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Insufficient role */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Conflicting state or idempotency key */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Validation failed */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  list_documents_v1_claims__claim_reference__documents_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        claim_reference: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DocumentView'][];
        };
      };
      /** @description Malformed request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Missing or invalid bearer token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Insufficient role */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Conflicting state or idempotency key */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Validation failed */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  request_upload_v1_claims__claim_reference__documents_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
        'Idempotency-Key'?: string | null;
      };
      path: {
        claim_reference: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['DocumentCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DocumentUploadTicket'];
        };
      };
      /** @description Malformed request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Missing or invalid bearer token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Insufficient role */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Conflicting state or idempotency key */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Validation failed */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  confirm_upload_v1_claims__claim_reference__documents__document_id__confirm_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        claim_reference: string;
        document_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['DocumentConfirm'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DocumentView'];
        };
      };
      /** @description Malformed request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Missing or invalid bearer token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Insufficient role */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Conflicting state or idempotency key */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Validation failed */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  download_url_v1_claims__claim_reference__documents__document_id__download_url_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        claim_reference: string;
        document_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DownloadTicket'];
        };
      };
      /** @description Malformed request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Missing or invalid bearer token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Insufficient role */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Conflicting state or idempotency key */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Validation failed */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  list_reserves_v1_claims__claim_reference__reserves_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        claim_reference: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ReserveView'][];
        };
      };
      /** @description Malformed request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Missing or invalid bearer token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Insufficient role */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Conflicting state or idempotency key */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Validation failed */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  create_reserve_v1_claims__claim_reference__reserves_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
        'Idempotency-Key'?: string | null;
      };
      path: {
        claim_reference: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ReserveCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ReserveResult'];
        };
      };
      /** @description Malformed request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Missing or invalid bearer token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Insufficient role */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Conflicting state or idempotency key */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Validation failed */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  create_settlement_v1_claims__claim_reference__settlements_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
        'Idempotency-Key'?: string | null;
      };
      path: {
        claim_reference: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SettlementCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PaymentView'];
        };
      };
      /** @description Malformed request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Missing or invalid bearer token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Insufficient role */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Conflicting state or idempotency key */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Validation failed */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  read_timeline_v1_claims__claim_reference__timeline_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        claim_reference: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TimelineEntry'][];
        };
      };
      /** @description Malformed request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Missing or invalid bearer token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Insufficient role */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Conflicting state or idempotency key */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Validation failed */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  create_transition_v1_claims__claim_reference__transitions_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
        'Idempotency-Key'?: string | null;
      };
      path: {
        claim_reference: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['TransitionCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TransitionView'];
        };
      };
      /** @description Malformed request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Missing or invalid bearer token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Insufficient role */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Conflicting state or idempotency key */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Validation failed */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  rerun_triage_v1_claims__claim_reference__triage_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        claim_reference: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TriageView'];
        };
      };
      /** @description Malformed request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Missing or invalid bearer token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Insufficient role */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Conflicting state or idempotency key */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Validation failed */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  current_rule_set_v1_rule_sets_current_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RuleSetView'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
}
